#!/bin/bash

# Thanks to Kevin Loughlin for sharing on the Piazza forum
# NOTE: this script should be placed in the same directory as the .java files to be run
# It must be made executable and saved without an extension to be run as required for CS 124

# Make sure you have 3 command line args
if [ $# -eq 3 ]
then
	java Main2 "$1" "$2" "$3"
else
	# else display error
	echo "Error: command line must be of the below form..."
	echo "./randmst 0 dimension inputfile"
fi
